class Color:
    def __init__(self, html=None):
        if html is not None:
            self.html = html
            self.r = html[:2]
            self.g = html[2:4]
            self.b = html[-2:]
            self.rgb = (int(self.r, 16), int(self.g, 16), int(self.b, 16))
            self.bgr = (int(self.b, 16), int(self.g, 16), int(self.r, 16))


class ColorPalette():
    def __init__(self):
        self.category = {
            'person': Color(html='00FFE0'),
            'animal': Color(html='FF7F00'),
            'vehicle': Color(html='2CFF00'),
            'unique id': Color(html='D391F9'),
            'epp': Color(html='FFFF00'),
            'other': Color(html='FFFFFF'),
        }
        self.coco = {
            'person': self.category['person'],
            'bicycle': self.category['vehicle'],
            'car': self.category['vehicle'],
            'motorcycle': self.category['vehicle'],
            'airplane': self.category['vehicle'],
            'bus': self.category['vehicle'],
            'train': self.category['vehicle'],
            'truck': self.category['vehicle'],
            'boat': self.category['vehicle'],
            'traffic light': self.category['other'],
            'fire hydrant': self.category['other'],
            'stop sign': self.category['other'],
            'parking meter': self.category['other'],
            'bench': self.category['other'],
            'bird': self.category['animal'],
            'cat': self.category['animal'],
            'dog': self.category['animal'],
            'horse': self.category['animal'],
            'sheep': self.category['animal'],
            'cow': self.category['animal'],
            'elephant': self.category['animal'],
            'bear': self.category['animal'],
            'zebra': self.category['animal'],
            'giraffe': self.category['animal'],
            'backpack': self.category['other'],
            'umbrella': self.category['other'],
            'handbag': self.category['other'],
            'tie': self.category['other'],
            'suitcase': self.category['other'],
            'frisbee': self.category['other'],
            'skis': self.category['other'],
            'snowboard': self.category['other'],
            'sports ball': self.category['other'],
            'kite': self.category['other'],
            'baseball bat': self.category['other'],
            'baseball glove': self.category['other'],
            'skateboard': self.category['other'],
            'surfboard': self.category['other'],
            'tennis racket': self.category['other'],
            'bottle': self.category['other'],
            'wine glass': self.category['other'],
            'cup': self.category['other'],
            'fork': self.category['other'],
            'knife': self.category['other'],
            'spoon': self.category['other'],
            'bowl': self.category['other'],
            'banana': self.category['other'],
            'apple': self.category['other'],
            'sandwich': self.category['other'],
            'orange': self.category['other'],
            'broccoli': self.category['other'],
            'carrot': self.category['other'],
            'hot dog': self.category['other'],
            'pizza': self.category['other'],
            'donut': self.category['other'],
            'cake': self.category['other'],
            'chair': self.category['other'],
            'couch': self.category['other'],
            'potted plant': self.category['other'],
            'bed': self.category['other'],
            'dining table': self.category['other'],
            'toilet': self.category['other'],
            'tv': self.category['other'],
            'laptop': self.category['other'],
            'mouse': self.category['other'],
            'remote': self.category['other'],
            'keyboard': self.category['other'],
            'cell phone': self.category['other'],
            'microwave': self.category['other'],
            'oven': self.category['other'],
            'toaster': self.category['other'],
            'sink': self.category['other'],
            'refrigerator': self.category['other'],
            'book': self.category['other'],
            'clock': self.category['other'],
            'vase': self.category['other'],
            'scissors': self.category['other'],
            'teddy bear': self.category['other'],
            'hair drier': self.category['other'],
            'toothbrush': self.category['other'],
            'other': self.category['other']
        }
